### ISSUE TITLE
"Reverse order" bug in files with properties.

### ISSUE THREAD

**Issue by TriplEight** [icealtria/obsidian-telegram-inbox#11]
Properties is yaml syntax in md files. They must follow the pattern below:
![image](https://github.com/user-attachments/assets/1e4a3401-37b3-49a3-aca4-dcdd95b75dc0)

![image](https://github.com/user-attachments/assets/a37ea8df-469c-4c68-b584-6ab5c2031eb6)

If the initial yaml predicate `---` does not start from the 1st line of the file, the properties will be broken.
This is how it looks like in Obsidian:
![image](https://github.com/user-attachments/assets/a392c449-5d58-4d55-9934-80b5c0259563)

**Comment by icealtria** [comment]
I  did not handle the case with frontmatter. Try 1.4.3, this issue should be fixed.

**Comment by TriplEight** [comment]
Thanks, it's not an issue now!
