### ISSUE TITLE
Send messages to a single note

### ISSUE THREAD

**Issue by tightness652** [icealtria/obsidian-telegram-inbox#2]
I'm not a big user of daily notes and have a single "scratchpad" note to write down ideas in. Is there any way of only saving the messages in one file instead of daily notes?

**Comment by icealtria** [comment]
No, currently saving messages to daily notes is the default behavior. 

However, I understand the need for a custom file option and will consider implementing it in the future.

**Comment by icealtria** [comment]
In version 1.2.0, I have added a feature that allows you to save messages to a custom file path. You can now specify a single "scratchpad" note or any other file to store your messages.
