### ISSUE TITLE
Add a feature to delay the start of bot after startup.

### ISSUE THREAD

**Issue by DilicalFlame** [icealtria/obsidian-telegram-inbox#4]
Please add a feature to delay the startup of bot. I am having a problem. 
My vault is set up for sync with dropbox via Remotely sync plugin, when I insert a few lines in daily note via this plugin it works excellent.

But when I open my vault in another device, insertion happens before sync. Because of this sync sends new data to dropbox and previous insertions are lost.

How to solve this problem? = Add a command pallet option to manually trigger start or simply give us an option in plugin settings to manually input after how much seconds we want the bot to start after obsidian startup.

If sync happens first then bot inserts the messages, data won't be lost.

**Comment by DilicalFlame** [comment]
Temporary Solution: I keep Telegram Inbox plugin disabled. So after opening my vault I make sure that sync is done first, then I turn on the plugin, all messages are inserted successfully. 
After successful insertion I disable the plugin again.

**Comment by icealtria** [comment]
I've added some features in the latest version that might help. You can now choose not to start the bot on startup, and there are commands to control the bot, start, stop, or get updates manually.

I think adding a delay is not a very elegant solution, I'm looking for a better way.
