### ISSUE TITLE
Instruction: how to show text output on Obsidian?

### ISSUE THREAD

**Issue by rotello** [icealtria/obsidian-telegram-inbox#6]
I know I am a noob but how do i receive the telegram text?
I added the {{{text}}} in the template and nothing happens dinamically.
I am sure I m doing something wrong, can you help?

**Comment by icealtria** [comment]
Is the Bot set up and connected successfully?

If the bot is working and you send it a message, you will receive a reaction❤️(success) or an error message.

**Comment by rotello** [comment]
Mmmhh I thought so... but i only get a double check and nothing else. i guess i m doing something wrong...

<img width="333" alt="Screenshot 2024-08-10 at 17 10 52" src="https://github.com/user-attachments/assets/416af28f-b283-4205-a66e-79584368ee65">

<img width="799" alt="Screenshot 2024-08-10 at 17 08 09" src="https://github.com/user-attachments/assets/f9d460a2-5946-4cfd-baf2-abd0ae0c1b08">
<img width="508" alt="Screenshot 2024-08-10 at 17 09 35" src="https://github.com/user-attachments/assets/7549f89e-7753-4c4f-a795-d3b665379b23">

**Comment by icealtria** [comment]
Actually "Validate" is just to make sure the syntax is correct. This is to avoid program errors. `{{{text_telegramBot}}}` is not valid. There is indeed some ambiguity here.

https://github.com/icealtria/obsidian-telegram-inbox/wiki/Message-template
Only these fields can be used. You may replace `{{{text_telegramBot}}}` with `{{{text}}}`.

Also, I noticed that there is no reaction❤️ in your telegram message. Have you added your username or id to **Allowed users**?
![image](https://github.com/user-attachments/assets/34fbdbf3-3e37-47b2-abff-a8258da108c0)

**Comment by rotello** [comment]
Thanks for your patience for my noob questions:

Let me recap:

Create a bot using [@BotFather](https://telegram.me/BotFather). - OK

Copy the bot token provided by [@BotFather](https://telegram.me/BotFather).
Paste the token into the Bot Token field in the plugin settings.
Add your username or telegram id to Allowed Users. You can get your id from [@Get_UIDbot](https://t.me/Get_UIDbot)

It was wrong - i Added the @ MyName istead of just MyName And now it does work
<img width="247" alt="Screenshot 2024-08-10 at 21 23 02" src="https://github.com/user-attachments/assets/13ca9bf8-b06f-4f3b-9cbe-faa8fd8e24ec">

Click the Restart button. DONE
  
Then:

Added {{{text}}} - {{time}} in the daily template... what should i expect now?

If I send a message to my bot, I should get an heart  OK 

<img width="379" alt="Screenshot 2024-08-10 at 21 37 53" src="https://github.com/user-attachments/assets/a49133a2-239c-43e1-b791-5be62c4b39ee">


and the message get delivered to obsidian everytime i create a new page? or it 's "live" ?

<img width="250" alt="Screenshot 2024-08-10 at 21 46 40" src="https://github.com/user-attachments/assets/4089aa2e-8abf-4d7b-a8bb-d7881369eb07">

Thanks!

**Comment by icealtria** [comment]
After send a message to the bot, you will get a text in your daily notes that according to the Settings > Core Plugins > Daily Notes. For today, the text be saved to "2024-08-11".

As long as Obsidian is running, this will be handled automatically.

**Comment by rotello** [comment]
We are done
I ve tried the custom path with Telegram-Inbox.md and it does work!
then i switched back  and it does work. it happens data at the end of the page and not where the {{{text}}} is but it does work! GREAT! Thank you man!
