### ISSUE TITLE
Not all messages are added to the daily note before its created

### ISSUE THREAD

**Issue by laughtingman** [icealtria/obsidian-telegram-inbox#9]
I write several messages to the bot almost at the same time when obsidian is off and the daily note has not yet been created.

When I start obsidian, the daily note is created, I see only the first message I wrote to the bot in it, but I don't see the rest. However, the bot marks all new messages as liked. I think it is a bug.

**Comment by icealtria** [comment]
This issue did not reproduce on mine.

This looks like a race condition bug. This is weird, the program doesn't handle messages concurrently. You can open the console with <kbd>Shift</kbd> + <kbd>I</kbd> and see what output there is.

**Comment by laughtingman** [comment]
The console log doesn't show anything about it, but I was able to figure out what the problem was. I disabled all third-party plugins and started enabling them one by one. The problem is in the **Templater** plugin. After the template is compiled, some lines at the end of the file disappear.

The template is applied once, exactly at the moment of creating a daily note. I think that it takes a snapshot of the text at the moment when the first message is already added, and then replaces all contents of the file. And while the text is being processed, your plugin adds more messages parallel to it that are lost after replacing by the templater.

Apparently, to solve this problem, I need to somehow make it so that messages are added to the note with a delay or only after the templater has worked. Any ideas?

**Comment by icealtria** [comment]
Please update to version 1.4.1, where I used a atomic method to modify files. See if that resolves the issue.

**Comment by laughtingman** [comment]
I'm afraid it got worse and after the update it stopped working completely 😥. The console and the bot shown an error:
```
Failed to insert text message to vault. Error: Cannot read properties of null (reading 'path') 
TypeError: Cannot read properties of null (reading 'path')
    at TelegramBot.insertMessageToVault (plugin:telegram-inbox:5823:55)
    at async eval (plugin:telegram-inbox:5785:7)
    at async eval (plugin:telegram-inbox:2576:7)
    at async eval (plugin:telegram-inbox:2502:7)
    at async eval (plugin:telegram-inbox:2576:7)
    at async eval (plugin:telegram-inbox:2502:7)
    at async eval (plugin:telegram-inbox:2576:7)
    at async eval (plugin:telegram-inbox:2502:7)
    at async eval (plugin:telegram-inbox:5765:7)
    at async eval (plugin:telegram-inbox:2502:7)
eval @ plugin:telegram-inbox:5786
```

**Comment by icealtria** [comment]
This is caused by the debug code added in version 1.4.0. However, the actual issue cannot be identified from these error messages. 

I removed it in the new version. If it still doesn't work, find 1.3.2 in the release, overwrite the current version.

**Comment by icealtria** [comment]
I installed Templater and enabled "Trigger Templater on new file creation," but I haven't noticed any messages loss. But I found that the file created by telegram inbox, are not generated according to the template.

I don't know how you configured this plugin. Can you provide more information?

**Comment by laughtingman** [comment]
I have updated the plugin to 1.4.2 now there are no errors in the console, but the data is still lost. I also noticed that messages were no longer automatically generated as unordered list so I fixed it by adding the minus symbol to the message template from `{{{text}}}` to `- {{{text}}}`.

My Templater script makes a fetch request to the internet and gets some current data from there, such as a weather report. Maybe this is the issue, as the whole template is not applied until the promise is done.

Then I install the Lazy Plugin Loader which allows you to run third-party plugins with a customizable delay and specified for Telegram Inbox a delay of 5 seconds after startup. And that solved my problem, now messages are not missing because Templater has time to execute. At any rate this will work as long as the Fetch request doesn't get stuck longer.

I don't know if you need to do anything about it now. Anyway, thanks for responding. Your plugin is very cool and useful for me.
